name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python -m unittest discover -s tests -p 'test_app.py'

  deploy:
    runs-on: ubuntu-latest

    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
        # Ajoutez ici vos étapes de déploiement, par exemple, le déploiement sur un serveur ou un cloud.

